time.sleep(0.07)
pyautogui.hotkey('win', 'r')
time.sleep(0.07)
pyautogui.write('cmd') 
time.sleep(0.07)
pyautogui.press('enter')
time.sleep(1.2)
pyautogui.write('adb shell exit') 
time.sleep(0.07)
pyautogui.press('enter')
time.sleep(0.07)
pyautogui.write('exit') 
time.sleep(0.07)
pyautogui.press('enter')
